bug fix: compute_reward for batch input
Farama-Foundation/Gymnasium-Robotics pull request #153
Opened 2023-05-19 03:47 UTC by nicehiro

# Description

Fix `compute_reward` function can not compute reward for batch input in `AntMaze` environment.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-05-19 13:16 UTC, rodrigodelazcano commented
Hi @nicehiro! Can you give me a bit more detail on what type of bug this is? Some code example.

Also, can you run `pre-commit`(https://pre-commit.com/) locally to fix the CI?

2023-05-19 13:18 UTC, rodrigodelazcano commented on gymnasium_robotics/envs/maze/maze.py
> +            return - (d > 0.45).astype(np.float32)
Why are you changing the reward function? With your implementation it returns -1 if the goal is not reached and 0 otherwise.

2023-06-15 20:57 UTC, pseudo-rnd-thoughts requested changes
@nicehiro The suggested reward change makes sense but as we are trying to preserve at unmaintained work, we are going to keep the reward function as is. 
If you want to use the alternative reward function, I would recommend using a reward wrapper to modify the value. 

Could you allow add a test that confirms the function works as expected with a single and multiple rewards
Otherwise, looks good to merge

2023-06-19 15:52 UTC, pseudo-rnd-thoughts commented
@nicehiro Could you add the multi-fetch environment in a different PR

2023-06-20 01:47 UTC, nicehiro commented
> @nicehiro Could you add the multi-fetch environment in a different PR

Yes. Sorry about that.

> Could you allow add a test that confirms the function works as expected with a single and multiple rewards

Yes. Is it ok I add a test in `tests/env/fetch/`?

2023-06-20 09:57 UTC, pseudo-rnd-thoughts commented
> Yes. Is it ok I add a test in tests/env/fetch/?

Yes, I think makes sense

2023-06-20 10:37 UTC, Kallinteris-Andreas commented on gymnasium_robotics/envs/maze/maze.py
> +            return -(d > 0.45).astype(np.float32)
fp64 not fp32

2023-06-20 23:07 UTC, rodrigodelazcano commented
I'm merging this. Thank you @nicehiro and for the reviews @pseudo-rnd-thoughts and @Kallinteris-Andreas

2023-06-20 23:07 UTC, merged

2023-06-21 07:28 UTC, Kallinteris-Andreas commented
@rodrigodelazcano changing the reward function, would require a new revision

2023-06-21 11:41 UTC, pseudo-rnd-thoughts commented
@Kallinteris-Andreas I think we should revert the reward function change but the batch input shouldn't require a change of version

2023-06-21 14:27 UTC, rodrigodelazcano commented
Sorry @pseudo-rnd-thoughts and @Kallinteris-Andreas . I thought the changes were made.

Can you make a PR with the old reward function?

2023-06-21 14:47 UTC, Kallinteris-Andreas commented
also, i have no idea what `axis=-1` does

2023-06-21 14:58 UTC, pseudo-rnd-thoughts commented
Yeah, we need testing for this as well

2023-06-21 15:06 UTC, nicehiro commented
Yes. This should work for single input and batch inputs both.

I’ve tested it long times ago. Sorry that I don’t have a laptop to test it
right now.

Rodrigo de Lazcano ***@***.***>于2023年6月21日 周三22:59写道：

> also, i have no idea what axis=-1 does
>
> Basically this is used to compute vector norms along a specific axis of a
> matrix, instead of an int norm of the full matrix. In this case the last
> axis.
>
> Since the fix is for computing rewards for batch inputs of achieved and
> desired goal this addition is required.
>
> Am I missing anything @nicehiro <https://github.com/nicehiro> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/153#issuecomment-1600999763>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEHTIQWMCA5NMXALEXVAH6LXMMD3PANCNFSM6AAAAAAYHH557E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-21 16:13 UTC, Kallinteris-Andreas commented
To clarify I know what `axis=1` does, but I do not know what `axis=-1` does.

2023-06-21 16:20 UTC, pseudo-rnd-thoughts commented
`-1` is the last axis I believe